Log:
  # 'info' or 'debug' or 'verbose'
  Level: "debug"
  
ExternalAPIs:
  DataSource:
    # will retry requesting if error occurred while calling endpoint
    RetryCount: 1
    RequestPricingData: "https://interview-requester-source.herokuapp.com/request"
    GetPricingData: "https://interview-requester-source.herokuapp.com/request"
  Destination:
    # will retry requesting if error occurred while calling endpoint
    RetryCount: 1
    UpdatePricingData: "https://band-interview-destination.herokuapp.com/update"
    GetUpdatedPricingData: "https://band-interview-destination.herokuapp.com/get_price"

DataFeeder:
  Cache:
    # setting Enable to false results in call destination for updated price every time 
    Enable: true
    DataSource: "./cache/data_source.json"
    Destination: "./cache/destination.json"
    # If destination data cache has not been updated longer than 3600 seconds, service will call endpoint for updating
    # only used in calling for destination updated price
    LiveTime: 3600
  
  # will updates pricing to destination if no previous update longer than 3600 seconds
  MaximumDelay: 60 
  # if current price is differ from latest price more than 0.1 then will update to destination immediatly
  DiffThreshold: 0.05
  # get new pricing every 10 seconds
  DataSourceInterval: 10 
  # check if we need to update to destination every 10 seconds
  DestinationInterval: 10
  # before getting the requested pricing
  WaitTime: 5 
  # will feed these symbols to destination
  Symbols:
    - "BTC"
    - "ETH"
    - "ADA"
    - "DOGE"
    - "UST"
    - "BAND"
    - "ALPHA"