Log:
  # 'info' or 'debug' or 'verbose'
  Level: "info"
  
ExternalAPIs:
  DataSource:
    # will retry requesting if error occurred while calling endpoint
    RetryCount: 1
    RequestPricingData: "https://interview-requester-source.herokuapp.com/request"
    GetPricingData: "https://interview-requester-source.herokuapp.com/request"
  Destination:
    # will retry requesting if error occurred while calling endpoint
    RetryCount: 1
    UpdatePricingData: "https://band-interview-destination.herokuapp.com/update"
    GetUpdatedPricingData: "https://band-interview-destination.herokuapp.com/get_price"

DataFeeder:
  # will updates pricing to destination if (current time - updated destination time > 3600)
  MaximumDelay: 3600 
  # if current price is differ from latest price more than 0.1 then will update to destination immediatly
  DiffThreshold: 0.1
  # get pricing from data source every 10 seconds
  Interval: 10 
  # wait time between request data source and getting the requested data source
  WaitTime: 5 
  # should recheck updated pricing to destination or not?
  EnableRecheck: true
  # will feed these symbols to destination
  Symbols:
    - "BTC"
    - "ETH"
    - "ADA"
    - "DOGE"
    - "UST"
    - "BAND"
    - "ALPHA"